export enum Cities {
	BRISBANE = 'r7hgdm',
	SYDNEY = 'r3gx2s',
	CANBERRA = 'r3dp5h',
	HOBART = 'r22u08',
	PERTH = 'qd66hr',
	DARWIN = 'qvv117',
	ADELAIDE = 'r1f93c',
	MELBOURNE = 'r1r0fu'
}

export enum RadarRegions {
	// New South Wales / ACT
	NSW_BREWARRINA = 'IDR933',
	NSW_CANBERRA_CAPTAINS_FLAT = 'IDR403',
	NSW_GRAFTON = 'IDR283',
	NSW_HILLSTON = 'IDR943',
	NSW_MOREE = 'IDR533',
	NSW_NAMOI_BLACKJACK_MOUNTAIN = 'IDR693',
	NSW_NEWCASTLE = 'IDR043',
	NSW_SYDNEY_TERREY_HILLS = 'IDR713',
	NSW_WAGGA_WAGGA = 'IDR553',
	NSW_WOLLONGONG_APPIN = 'IDR033',
	NSW_YEOVAL = 'IDR963',
	NSW_NORFOLK_ISLAND = 'IDR623',
	
	// Victoria
	VIC_BAIRNSDALE = 'IDR683',
	VIC_MELBOURNE = 'IDR023',
	VIC_MILDURA = 'IDR973',
	VIC_RAINBOW = 'IDR953',
	VIC_YARRAWONGA = 'IDR493',
	
	// Queensland
	QLD_BOWEN = 'IDR243',
	QLD_BRISBANE_MARBURG = 'IDR503',
	QLD_BRISBANE_MT_STAPYLTON = 'IDR663',
	QLD_CAIRNS = 'IDR193',
	QLD_EMERALD = 'IDR723',
	QLD_GLADSTONE = 'IDR233',
	QLD_GREENVALE = 'IDR743',
	QLD_GULF_MORNINGTON_ISLAND = 'IDR363',
	QLD_GYMPIE_MT_KANIGAN = 'IDR083',
	QLD_LONGREACH = 'IDR563',
	QLD_MACKAY = 'IDR223',
	QLD_MOUNT_ISA = 'IDR753',
	QLD_RICHMOND = 'IDR1073',
	QLD_TAROOM = 'IDR983',
	QLD_TOOWOOMBA = 'IDR1083',
	QLD_TOWNSVILLE = 'IDR1063',
	QLD_WARREGO = 'IDR673',
	QLD_WEIPA = 'IDR783',
	QLD_WILLIS_ISLAND = 'IDR413',
	
	// South Australia
	SA_ADELAIDE_BUCKLAND_PARK = 'IDR643',
	SA_ADELAIDE_SELLICKS_HILL = 'IDR463',
	SA_CEDUNA = 'IDR333',
	SA_MOUNT_GAMBIER = 'IDR143',
	SA_WOOMERA = 'IDR273',
	
	// Western Australia
	WA_ALBANY = 'IDR313',
	WA_BROOME = 'IDR173',
	WA_CARNARVON = 'IDR1143',
	WA_DAMPIER = 'IDR343',
	WA_ESPERANCE = 'IDR353',
	WA_GERALDTON = 'IDR063',
	WA_GILES = 'IDR443',
	WA_HALLS_CREEK = 'IDR393',
	WA_KALGOORLIE = 'IDR483',
	WA_LEARMONTH = 'IDR293',
	WA_NEWDEGATE = 'IDR383',
	WA_PERTH_SERPENTINE = 'IDR703',
	WA_PORT_HEDLAND = 'IDR323',
	WA_SOUTH_DOODLAKINE = 'IDR583',
	WA_WATHEROO = 'IDR793',
	
	// Northern Territory
	NT_ALICE_SPRINGS = 'IDR253',
	NT_DARWIN_BERRIMAH = 'IDR633',
	NT_GOVE = 'IDR1123',
	NT_KATHERINE_TINDAL = 'IDR423',
	NT_WARRUWI = 'IDR773',
	
	// Tasmania
	TAS_HOBART_MT_KOONYA = 'IDR763',
	TAS_WEST_TAKONE = 'IDR523'
}
